### PR TITLE
Support for Julia 1

### PR DESCRIPTION
**Pull request by essenciary**
All the code in the README works fine. One test is failing though so maybe you can check that.

### CODE REVIEW

**Comment by colinfang** [comment]
oh, thank you. I will take a look & make a release for Julia v1.0

**Comment by essenciary** [comment]
👍

**Comment by colinfang** [comment]
I have tagged a new version v0.2.0 which should work with Julia v0.7+

Please have a look.

One change is you have to explicitly shadow the macros from `Base` like the following.

```julia
using MiniLogging
# Explicitly shadow Base
using MiniLogging: @debug, @info, @warn, @error, @critical
```

**Comment by essenciary** [comment]
Thanks - I'm setting up the integration now.

**Comment by colinfang** [comment]
@essenciary Sorry I meant the master branch & Registry version is already Julia v1.0 friendly. So you can install normally via `Pkg.add("MiniLogging")` and make sure it is v0.2.0.

I didn't work on your pr because I don't know how to add commit in your branch. Sorry about that.

**Comment by essenciary** [comment]
@colinfang Thanks, no worries, that's what I tried anyway, the registered version ;)

**Pull request closed without merging**
